### ISSUE TITLE
Transifex Translation

### ISSUE THREAD

**Issue by danimaribeiro** [odoomrp/odoomrp-utils#101]
I did the portuguese translation to odoomrp-utils, but now I don't know f you guys sinchronize that from the transifex.

Can you tell me if the translations will be updated from there, or I have to make a PR here?

**Comment by pedrobaeza** [comment]
I'm making the synchronization manually. It doesn't work automatically because the organization is not the same (odoomrp against OCA). I'll tell you when done.

**Comment by danimaribeiro** [comment]
Nice :+1: 
I'm also translating odoo-mrp.
