### ISSUE TITLE
sale_order_line_form_button No save button on editing form

### ISSUE THREAD

**Issue by youring** [odoomrp/odoomrp-utils#12]
sale_order_line_form_button
No "Save" button on editing form, but "Create Invoice" button appeared in top status bar which should be removed.

**Comment by pedrobaeza** [comment]
Hi, @youring, that it's standard functionality. You have save and discard button at the bottom of the popup screen (maybe you have to scroll down).

Close this issue as invalid.

**Comment by youring** [comment]
Hi pedrobaeza, I have re-tested it in Odoo 8 latest code, clean database with sale module installed. But still no Save and Discard button appeared at the bottom.

BTW: is there a runbot integration for odoomrp?

Thanks for the quick response.

**Comment by anajuaristi** [comment]
Hi @youring 
Sale.order.line tree view is an utility simply to be able to group and make several statistics, but it's not allowed to include new lines.
You should create new lines for SO directly inside the SO.

About runbot for odoomrp, there is not an integration for it. Sorry. We would like to have it but it has not been possible by the moment.

Thank you:
Ana
