### ISSUE TITLE
[8.0] mrp_production_unreserve_movements	 dependency?

### ISSUE THREAD

**Issue by jlaloux** [odoomrp/odoomrp-utils#137]
Hi,

I wanted to try your module named "mrp_production_unreserve_movements" but i see that it depends on module "mrp_operations_extension". I went to "Odoo app store" and on the repository related (https://github.com/odoomrp/odoomrp-wip#8.0) to this module, i don't find it. Does this module work? Can you tell me where i can find the dependency on github?

Thank you very much

**Comment by pedrobaeza** [comment]
mrp_operations_extension has been moved to OCA/manufacture: https://github.com/OCA/manufacture/tree/8.0/mrp_operations_extension
