### ISSUE TITLE
V8 mrp_production_unreserve_movements module -Order status Issue

### ISSUE THREAD

**Issue by sdalexander** [odoomrp/odoomrp-utils#147]
Hi @pedrobaeza @anajuaristi 

I have installed the above module , and it does as it says with the move lines. However it does leave the Production Order status  at whatever status it was before the unreserve.

So if it was 'ready to produce' and you click 'unreserve' it will still leave the status as 'ready to produce'.
I have tested on runbot today, using MO0001 (see attached)

![unreserve status issue](https://cloud.githubusercontent.com/assets/9946014/20528939/1c2d639e-b0c6-11e6-8ab4-ad0d0ef2c364.PNG)

This MO was short of the computer case and the Imac, so I added inventory for those items.

then checked availability on MO0001 , this allocated the components and changed the order status to 'ready to produce'.

then I clicked on 'Unreserve' and that has released the lines and set them  back to awaiting availability.

but the Order status is still 'ready to produce'

would this be possible to fix?

regards
 Steve

**Comment by Daniel-CA** [comment]
Not an easy change because when the order has all the products to start the production (reserved) the workflow of the MO goes to next step and is not possible to undo this, so even if the product is "unreserved" the production state should be in "ready to produce" to maintain workflow logic.

**Comment by StefanRijnhart** [comment]
For the record, I believe this is implemented in https://github.com/odoomrp/odoomrp-utils/pull/144
