### ISSUE TITLE
[IMP] No 10.0 Branch available for this repo?

### ISSUE THREAD

**Issue by atchuthan** [odoomrp/odoomrp-utils#150]
We had a need to use partner_address_type_default for Odoo v10 and planned to provide PR for it.  But, it seems the 10.0 branch doesn't exist.  Is it probably not maintained for v10.0 due to some technical reasons?

**Comment by atchuthan** [comment]
cc: @pedrobaeza @oihane

**Comment by pedrobaeza** [comment]
The idea is to move these modules to OCA, so please extract it and propose it directly to OCA.

**Comment by atchuthan** [comment]
@pedrobaeza ok, we will send the PR to https://github.com/OCA/partner-contact/
