### ISSUE TITLE
product_expiry_ext v10.0

### ISSUE THREAD

**Issue by gaelTorrecillas** [odoomrp/odoomrp-utils#171]
hello  @pedrobaeza,

I find product_expiry_ext for odoo 10.0.
I read that you used OCA for the next versions and developments.
But I didn't find it on OCA, do you have a topic to know where are yours odoomrp modules on OCA? Or more information about this module?

**Comment by pedrobaeza** [comment]
Hi, several modules have been moved to OCA, but this one is not very interesting for us now, so it hasn't been migrated nor moved. If you are interested, feel free to take it and move it, migrate it or whatever you want.
