### ISSUE TITLE
Filtro por número de claim (solicitud interna)

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-utils#18]
Buenas... 
Necesito que se añada el filtro por número de secuencia en el módulo crm_claim_sequence.

Es un rollo no poder buscar por número.

**Comment by pedrobaeza** [comment]
Se puede buscar con la búsqueda avanzada.

**Comment by anajuaristi** [comment]
Ya pero sinceramente... es un p. coñazo. Por los 10m que nos cuesta meter el filtro... por fa... ;)

**Comment by pedrobaeza** [comment]
Vale, venga, anda :stuck_out_tongue:

**Comment by anajuaristi** [comment]
@alfredoavanzosc Pues eso... Habría que modificar el módulo crm_claim_sequence o algo así creo que se llama. 
si no está aquí en utils, está en wip  o en nuestra rama avanzosc. Mira a ver.
Aprovechando la tesitura, si no está en utils, lo movería ya

**Comment by pedrobaeza** [comment]
Aprovechando que se le da una vuelta, Alfredo, mira cómo he hecho yo en este módulo (https://github.com/OCA/hr/pull/70) para:
- Filtrar directamente con el campo principal por la descripción o por el código.
- Asignar un nº de secuencia en tiempo de instalación a todos los ya existentes.

Es lo mismo, pero una secuencia para los gastos.

**Comment by alfredoavanzosc** [comment]
Realizado, y subido el módulo en PR https://github.com/avanzosc/odoo-addons/pull/7

**Comment by oihane** [comment]
Mergeado cierro
