### ISSUE TITLE
Ajustes stock plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-utils#60]
Buenas... probado el módulo en local hemos visto las siguientes cosillas
1. Incluir filtro para mostrar únicamente los que incremento requerido sea > 0
2. Agrupación por semana
3. Action para navegar a abastecimientos (Shorcut)
4. Help en campos del wizard
5. Filtro y agrupación por categoría de producto
6. Filtro por producto, ubicación, cía y almacén
7. En el Wizard de lanzamiento meter también filtro por categoría / plantilla / producto 
8. Cantidad a pedir, si sale más del máximo, poner la cantidad en negativo y no cero
9. Poner colores según la cantidad a pedir. Si es negativa en naranja, si es positiva en rojo y si es cero en verde.

**Comment by alfredoavanzosc** [comment]
Cantidad a pedir mayor que la cantidad máxima de la regla?. No entiendo en que caso aparece cero, y hay que poner en negativo.

**Comment by anajuaristi** [comment]
Si, se supone que la fórmula te calcula una cantidad basada en el campo mínimo. Actualmente solo calcula la cantidad a pedir o pone cero. Pero puede darse el caso que el entrante - saliente sea mayor que el campo máximo, esto quiere decir que a una fecha tenemos material de sobra, por lo que igual necesitamos cancelar un abastecimiento o algo. Es por eso.

**Comment by alfredoavanzosc** [comment]
Ana... esto ya esta hecho, solo comentarte una cosa sobre el punto número 6, cuando pides "Filtro por producto, ubicación, cía y almacén". A estos campos no se les puede poner un filtro, si no les pones un valor en concreto, como en el caso del punto número 1.
Si quieres filtrar por producto, ubicación, cía, y almacén, lo tendrás que hacer en el campo de "search".
Comentarte también que el módulo esta en nuestro servidor, TRAVIS me está dando error, pero es algún tema de ellos, ya se lo he comentado a Pedro.
Tienes disponible esta última versión en el servidor de la ofi, tendrás que actualizar el módulo.
