### ISSUE TITLE
Cambiar pedido a terminado manualmente

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-utils#79]
Poder dar por terminado un pedido de forma manual, aunque no esté facturado o enviado totalmente, ya que hay ocasiones en que un cliente abandona el pedido sin terminarlo y no es práctico tenerlo sin terminar.

@pedrobaeza 

> Bueno, se puede terminar un workflow manualmente, por lo que técnicamente es viable. Lo acepto en alcance.

Como se haría para terminar un workflow manualmente, te suena hay algún ejemplo donde pueda mirar?

**Comment by pedrobaeza** [comment]
Con `trg_delete` puedes directamente matar un workflow a medias.
