### ISSUE TITLE
Crear órdenes de compras desde órden de producción con cantidades basadas en stock

### ISSUE THREAD

**Issue by gabrielo77** [odoomrp/odoomrp-utils#86]
Hola , quizá puedan darme una mano con este tema:

Si se trabaja en odoo v8 (creo que en versiones anteriores pasaba lo mismo) con el módulo de mrp cuando se define la fabricación de una pieza que contiene una lista de materiales pasa lo siguiente

Supongamos que uno de los componentes de la pieza a fabricar es el producto P . Si a P se lo define como "make to order" en la parte de abastecimientos, cuando se envía a fabricar la pieza que contiene a P , se genera un pedido de presupuesto por la cantidad de P necesarios para cumplimentar la orden de fabricación , SIN CHEQUEAR las condiciones de P en stock

Es decir si yo necesito 3 P y tengo 2 P en stock ( con lo cual debería comprar 1 solamente o al menos chequear contra la regla de reposición mínima que tenga definido P ) , el open lo ignora completamente y se manda a hacer el pedido de presupuesto por 3P

Estuve buscando en foros y el problema al menos en un foro del 2013 está descripto tal cual lo describo pero nadie pone una solución.

Puedo resolver esto con alguno de los módulos que se encuentrar aqui? O hay que usar alguna configuración en particular?

gracias desde ya por la ayuda

**Comment by pedrobaeza** [comment]
Prueba este módulo para utilizar MTS+MTO: https://github.com/OCA/stock-logistics-warehouse/tree/8.0/stock_mts_mto_rule

**Comment by gamarino** [comment]
Gabriel:
El tema es que es lo que querés lograr.

El MTO genera siempre un abastecimiento al confirmar la OV.

El MTS checkea stock y de faltar genera la orden (que entiendo es lo que
estás buscando)

Si fijas el producto como MTS, con stock mínimo 0, cuando pidas los tres
productos, checkeará contra los dos en stock y va a generar un pedido de
presupuesto por la unidad faltante. Mejor todavía si instalas el módulo
procurement_jit el pedido se genera al momento de confirmar la Orden de
venta. Sin este módulo tenés que esperar el scheduler.

Podes probar tambien el módulo de Pedro que agrega más posibilidades

Saludos

Gustavo Adrian Marino

Mobile:  +54 911 5498 2515

Email: gamarino@numaes.com

Skype: gustavo.adrian.marino

[image: Descripción: Numa Logo V 1-0]

2015-09-02 16:39 GMT-03:00 Pedro M. Baeza notifications@github.com:

**Comment by gabrielo77** [comment]
Gustavo, gracias por tu respuesta.

Tenemos instalado el procurement_jit, no creo que venga por ahi. Por la
descripción del módulo que dice Pedro, es exactamente eso lo que
necesitamos. Todavía no lo pude probar, apenas tenga tiempo lo hago y
comento los resultados.

Muchas gracias a ambos.

## 

Gabriel.

**Comment by gabrielo77** [comment]
No logré hacerlo andar, cargué los issues 83 y 84 en el repositorio del módulo.

Gracias por su tiempo.
