### ISSUE TITLE
Stock planning: Detectado un pequeño bug cuando está instalado purchase requisition y cambio en fórmulas

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-utils#90]
Buenas...

Cuando está instalado purchase requisition, existen 2 estados más del pedido de compra aparte de "draft" donde el pedido está creado, pero aún no ha sido confirmado y por tanto no ha sido creado el movimiento de entrada.
Por tanto, creo que en aquellos lugares donde la condicion es purchase.order.status = 'Draft' debería ser not in cancel, done, exception.

Un ejemplo:
https://github.com/odoomrp/odoomrp-utils/blob/8.0/stock_planning/models/stock_planning.py#L63

habría que cambiar la condición 

```
        for procurement in procurements:
            if (not procurement.purchase_id or
                (procurement.purchase_id and procurement.purchase_id.state ==
                 'draft')):
```

Para que sea 

```
        for procurement in procurements:
            if (not procurement.purchase_id or
                (procurement.purchase_id and procurement.purchase_id.state not in(
                 'cancel', 'Done', 'exception")):
```

(con la sintaxis que sea necesaria)

---

Aparte, me he dado cuenta que SOLO estamos teniendo en cuanta presupuestos de compra, que hayan sido creados desde abastecimientos, pero no los que se han creado a mano, lo cual desvirtúa los datos.
Tampoco estamos teniendo en cuenta órdenes de fabricación en borrador, que igualmente pueden estar asociados a abastecimientos o no.

Pongo todos los campos que tenemos y cómo los cambiaría:
Company  --> CORRECTO
Warehouse --> CORRECTO
Location --> CORRECTO
Scheduled date --> Verificar en el wizard cómo se construye. Tendría que crear una fila por cada X días que se pone en el wizard y no crea todas.
Product --> CORRECTO
Quantity On Hand --> CORRECTO 
Forecast Quantity --> CORRECTO
Incoming --> CORRECTO
Outgoing --> CORRECTO
Incoming up to date from moves --> CORRECTO 
Incoming up to date from procurements --> COGER SOLO procurements en estado "confirmado"

AÑADIR campo nuevo --> Incoming in PO --> Añadir sumatorio de cantidad de líneas de presupuestos de compra, que lleven ese producto a fecha, en estado <> (draft, done, exception)
AÑADIR campo nuevo --> Incoming in MO --> Añadir sumatorio de cantidad de MOs que lleven ese producto (producto final) a fecha en estado Draft

Outgoing to date --> Correcto 
Scheduled to date --> Stock real actual en la ubicación + Incoming up to date from procurements +  Incoming in PO +  Incoming in MO - Outgoing to date

Rule min. qty --> Correcto 
Rule max. qty  --> Correcto

Required increase -->
      Si Scheduled to date < Rule min. qty coger el máximo entre Scheduled to date y Rule max. qty
Actualmente está haciendo algo raro en el cálculo. Tiene pinta que está cogiendo el Rule min qty.

---

Por último, ya que hemos añadido 2 campos nuevos, añadir los 2 correspondientes links en las líneas, para que nos lleve directamente a los pedidos de compra implicados y a las órdenes de fabricación implicadas en los cálculos.

**Comment by alfredoavanzosc** [comment]
@anajuaristi ... dices que instalando el módulo "purchase_requision", al campo "state" de los pedidos de compra, se le meten 2 estados nuevos. Bueno... este módulo no mete ningún estado nuevo a los pedidos de compra. Lo que si veo es que el propio módulo "purchase" tiene los estados del pedido de compra 'except_picking' y 'except_invoice". En vez del estado que pones tu, "exception", son estos 2 estados los que tengo que meter?.

**Comment by alfredoavanzosc** [comment]
Para el cálculo del nuevo campo "Incoming in PO", a parte del campo state que se ha hablado en el punto anterior, no se habla nada de que ubicación hay que tener en cuenta, a la hora de seleccionar líneas de pedido de compra.
